services:
  getting-started:
    container_name: getting-started
    image: docker/getting-started:latest
    restart: unless-stopped
    ports:
      - 80:80

networks:
  default: 
    name: getting-started